### ISSUE TITLE
Update fiddle

### ISSUE THREAD

**Issue by martinvd** [jillesme/AdBlockCheck#2]
The `<h1>` tags in the [demo](http://jsfiddle.net/jillesme/ejq98wem/) that shows whether AdBlock is enabled or not, shows in both cases 'enabled'.

**Comment by jillesme** [comment]
Cheers! Fixed.. I just reset the JSFiddle base so that's why you won't see a commit. Thanks for spotting this!

**Comment by martinvd** [comment]
Welcome! :smiley:
